import 'package:meta/meta.dart';

/// DO NOT EDIT – generated by scripts/update-js.sh
@internal
const sentryJsSdkVersion = '11.4.0';

@internal
const productionIntegrity =
    'sha384-leCZtyH0v+/d38CQgHkDf/buaYk8uIH2vrAwzlLXVLKTcrvUWEUGan36c9ooM12N';

@internal
const debugIntegrity =
    'sha384-3Tc/6YQisDjdflZxVHwIGfgdd0F7OYPtNAWMBFuqzQi32c2j2bj0PzR8JCzqrVFT';
