import 'package:meta/meta.dart';

/// DO NOT EDIT – generated by scripts/update-js.sh
@internal
const sentryJsSdkVersion = '10.74.0';

@internal
const productionIntegrity =
    'sha384-CCezsb0qbfbnbzcRDSy3XlHzSU07iIC4skHulLBwZKmpUT1mGzkLRYB1NWry9XPY';

@internal
const debugIntegrity =
    'sha384-YOJGW1X4sr7wbVmLfx+k5IHcAcYO7lvV8m6dcdoI6wTDrT8xxiTlarZBhWgiBjwS';
