import 'package:meta/meta.dart';

/// DO NOT EDIT – generated by scripts/update-js.sh
@internal
const sentryJsSdkVersion = '10.73.0';

@internal
const productionIntegrity =
    'sha384-hg+m2gH9OTwLWydPV8rT7sz0kLIp9u9BxTvWnb+htzr1DJfGKk5e8JRLg92vUDOJ';

@internal
const debugIntegrity =
    'sha384-BdmnUikgTNy6sCsFZW0reg1I0R3ZVjG/Zw+J6D2FEhjPczC+sjrcxm8bDPk655Gq';
